import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import { ThemeProvider } from "@/providers/theme-provider";
import { BackendDataProvider } from "@/src/context/BackendDataContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "QuantCopierMT5-Telegram",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <BackendDataProvider>
            {children}
            <Toaster />
          </BackendDataProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
